const fancyNameArray = [
  ['Adorable', 'Amber', 'Beaver'],
  ['Adventurous', 'Amethyst', 'Bee'],
  ['Agile', 'Apricot', 'Canary'],
  ['Amazing', 'Arboreal', 'Cat'],
  ['Ancient', 'Arctic', 'Catfish'],
  ['Artistic', 'Banana', 'Centaur'],
  ['Astounding', 'Blue', 'Chicken'],
  ['Athletic', 'Brass', 'Coyote'],
  ['Awesome', 'Cave', 'Cricket'],
  ['Beautiful', 'Celestial', 'Dinosaur'],
  ['Benevolent', 'Citrine', 'Dog'],
  ['Big', 'Cloud', 'Dolphin'],
  ['Blazing', 'Cobalt', 'Dragon'],
  ['Blissful', 'Copper', 'Dragonfly'],
  ['Blushing', 'Crystal', 'Eagle'],
  ['Bold', 'Desert', 'Elephant'],
  ['Bouncy', 'Diamond', 'Falcon'],
  ['Breezy', 'Emerald', 'Flamingo'],
  ['Bright', 'Fire', 'Fox'],
  ['Brilliant', 'Forest', 'Giraffe'],
  ['Bubbly', 'Fuchsia', 'Grasshopper'],
  ['Bumpy', 'Gold', 'Griffin'],
  ['Busy', 'Gray', 'Hamster'],
  ['Calm', 'Green', 'Hawk'],
  ['Camouflaged', 'Indigo', 'Hippogriff'],
  ['Carefree', 'Jade', 'Hippopotamus'],
  ['Caring', 'Jungle', 'Horse'],
  ['Carnivorous', 'Lava', 'Inchworm'],
  ['Charming', 'Lavender', 'Kitten'],
  ['Cheerful', 'Lightning', 'Kraken'],
  ['Cheesy', 'Lime', 'Lemur'],
  ['Classy', 'Magenta', 'Leopard'],
  ['Colossal', 'Maroon', 'Lion'],
  ['Comfortable', 'Moonstone', 'Lizard'],
  ['Cool', 'Mountain', 'Manatee'],
  ['Corny', 'Navy', 'Monkey'],
  ['Courageous', 'Ocean', 'Narwhal'],
  ['Cozy', 'Olive', 'Octopus'],
  ['Crawling', 'Onyx', 'Parrot'],
  ['Crazy', 'Opal', 'Phoenix'],
  ['Creative', 'Orange', 'Platypus'],
  ['Cuddly', 'Pearl', 'Pony'],
  ['Cunning', 'Pink', 'Porcupine'],
  ['Dainty', 'Platinum', 'Puppy'],
  ['Dancing', 'Plum', 'Raccoon'],
  ['Dapper', 'Purple', 'Rooster'],
  ['Daring', 'Quartz', 'Seahorse'],
  ['Dark', 'Rainforest', 'Sloth'],
  ['Dashing', 'Red', 'Slug'],
  ['Delightful', 'River', 'Snail'],
  ['Deluxe', 'Ruby', 'Sphinx'],
  ['Determined', 'Sand', 'Squid'],
  ['Doubtful', 'Sapphire', 'Squirrel'],
  ['Dreaming', 'Scarlet', 'Stegosaurus'],
  ['Dry', 'Silver', 'Tiger'],
  ['Educated', 'Sky', 'Timberwolf'],
  ['Elder', 'Snow', 'Tuna'],
  ['Endearing', 'Space', 'Tyrannosaurus'],
  ['Energetic', 'Tangerine', 'Unicorn'],
  ['Engaging', 'Teal', 'Velociraptor'],
  ['Enormous', 'Titanium', 'Walrus'],
  ['Entertaining', 'Topaz', 'Whale'],
  ['Exciting', 'Violet', 'Wolf'],
  ['Extraordinary', 'Yellow', 'Zebra'],
  ['Fanciful', 'Amber', 'Beaver'],
  ['Fantastic', 'Amethyst', 'Bee'],
  ['Fast', 'Apricot', 'Canary'],
  ['Fearless', 'Arboreal', 'Cat'],
  ['Feathered', 'Arctic', 'Catfish'],
  ['Feisty', 'Banana', 'Centaur'],
  ['Feral', 'Blue', 'Chicken'],
  ['Fierce', 'Brass', 'Coyote'],
  ['Floppy', 'Cave', 'Cricket'],
  ['Fluffy', 'Celestial', 'Dinosaur'],
  ['Flying', 'Citrine', 'Dog'],
  ['Friendly', 'Cloud', 'Dolphin'],
  ['Frosty', 'Cobalt', 'Dragon'],
  ['Funny', 'Copper', 'Dragonfly'],
  ['Furry', 'Crystal', 'Eagle'],
  ['Fuzzy', 'Desert', 'Elephant'],
  ['Galactic', 'Diamond', 'Falcon'],
  ['Gargantuan', 'Emerald', 'Flamingo'],
  ['Generous', 'Fire', 'Fox'],
  ['Gentle', 'Forest', 'Giraffe'],
  ['Genuine', 'Fuchsia', 'Grasshopper'],
  ['Giant', 'Gold', 'Griffin'],
  ['Giggly', 'Gray', 'Hamster'],
  ['Ginormous', 'Green', 'Hawk'],
  ['Glacial', 'Indigo', 'Hippogriff'],
  ['Glamorous', 'Jade', 'Hippopotamus'],
  ['Gleeful', 'Jungle', 'Horse'],
  ['Glistening', 'Lava', 'Inchworm'],
  ['Glittery', 'Lavender', 'Kitten'],
  ['Glossy', 'Lightning', 'Kraken'],
  ['Glowing', 'Lime', 'Lemur'],
  ['Good', 'Magenta', 'Leopard'],
  ['Goofy', 'Maroon', 'Lion'],
  ['Gorgeous', 'Moonstone', 'Lizard'],
  ['Graceful', 'Mountain', 'Manatee'],
  ['Great', 'Navy', 'Monkey'],
  ['Groovy', 'Ocean', 'Narwhal'],
  ['Grumpy', 'Olive', 'Octopus'],
  ['Gutsy', 'Onyx', 'Parrot'],
  ['Hairy', 'Opal', 'Phoenix'],
  ['Happy', 'Orange', 'Platypus'],
  ['Heavy', 'Pearl', 'Pony'],
  ['Helpful', 'Pink', 'Porcupine'],
  ['Heroic', 'Platinum', 'Puppy'],
  ['Hidden', 'Plum', 'Raccoon'],
  ['Hopeful', 'Purple', 'Rooster'],
  ['Hopping', 'Quartz', 'Seahorse'],
  ['Huge', 'Rainforest', 'Sloth'],
  ['Humongous', 'Red', 'Slug'],
  ['Humorous', 'River', 'Snail'],
  ['Hungry', 'Ruby', 'Sphinx'],
  ['Hyper', 'Sand', 'Squid'],
  ['Icy', 'Sapphire', 'Squirrel'],
  ['Idealistic', 'Scarlet', 'Stegosaurus'],
  ['Imaginative', 'Silver', 'Tiger'],
  ['Impressive', 'Sky', 'Timberwolf'],
  ['Incredible', 'Snow', 'Tuna'],
  ['Ingenious', 'Space', 'Tyrannosaurus'],
  ['Inky', 'Tangerine', 'Unicorn'],
  ['Innovative', 'Teal', 'Velociraptor'],
  ['Inspiring', 'Titanium', 'Walrus'],
  ['Intellectual', 'Topaz', 'Whale'],
  ['Interesting', 'Violet', 'Wolf'],
  ['Interstellar', 'Yellow', 'Zebra'],
  ['Intrepid', 'Amber', 'Beaver'],
  ['Itty-Bitty', 'Amethyst', 'Bee'],
  ['Jazzy', 'Apricot', 'Canary'],
  ['Jiggly', 'Arboreal', 'Cat'],
  ['Joking', 'Arctic', 'Catfish'],
  ['Jovial', 'Banana', 'Centaur'],
  ['Joyful', 'Blue', 'Chicken'],
  ['Jumpy', 'Brass', 'Coyote'],
  ['Lacy', 'Cave', 'Cricket'],
  ['Large', 'Celestial', 'Dinosaur'],
  ['Laughing', 'Citrine', 'Dog'],
  ['Lazy', 'Cloud', 'Dolphin'],
  ['Leafy', 'Cobalt', 'Dragon'],
  ['Light', 'Copper', 'Dragonfly'],
  ['Lively', 'Crystal', 'Eagle'],
  ['Long', 'Desert', 'Elephant'],
  ['Loony', 'Diamond', 'Falcon'],
  ['Loud', 'Emerald', 'Flamingo'],
  ['Lovely', 'Fire', 'Fox'],
  ['Loyal', 'Forest', 'Giraffe'],
  ['Lucky', 'Fuchsia', 'Grasshopper'],
  ['Lyrical', 'Gold', 'Griffin'],
  ['Magical', 'Gray', 'Hamster'],
  ['Magnetic', 'Green', 'Hawk'],
  ['Majestic', 'Indigo', 'Hippogriff'],
  ['Marvelous', 'Jade', 'Hippopotamus'],
  ['Masterful', 'Jungle', 'Horse'],
  ['Mega', 'Lava', 'Inchworm'],
  ['Merry', 'Lavender', 'Kitten'],
  ['Metallic', 'Lightning', 'Kraken'],
  ['Micro', 'Lime', 'Lemur'],
  ['Mighty', 'Magenta', 'Leopard'],
  ['Mini', 'Maroon', 'Lion'],
  ['Mischievous', 'Moonstone', 'Lizard'],
  ['Muscular', 'Mountain', 'Manatee'],
  ['Musical', 'Navy', 'Monkey'],
  ['Mutant', 'Ocean', 'Narwhal'],
  ['Mysterious', 'Olive', 'Octopus'],
  ['Mythical', 'Onyx', 'Parrot'],
  ['Nice', 'Opal', 'Phoenix'],
  ['Nocturnal', 'Orange', 'Platypus'],
  ['Noticeable', 'Pearl', 'Pony'],
  ['Optimistic', 'Pink', 'Porcupine'],
  ['Outdoorsy', 'Platinum', 'Puppy'],
  ['Painted', 'Plum', 'Raccoon'],
  ['Patient', 'Purple', 'Rooster'],
  ['Peaceful', 'Quartz', 'Seahorse'],
  ['Perfect', 'Rainforest', 'Sloth'],
  ['Persistent', 'Red', 'Slug'],
  ['Pigmy', 'River', 'Snail'],
  ['Playful', 'Ruby', 'Sphinx'],
  ['Polite', 'Sand', 'Squid'],
  ['Powerful', 'Sapphire', 'Squirrel'],
  ['Quick', 'Scarlet', 'Stegosaurus'],
  ['Quiet', 'Silver', 'Tiger'],
  ['Quirky', 'Sky', 'Timberwolf'],
  ['Random', 'Snow', 'Tuna'],
  ['Remarkable', 'Space', 'Tyrannosaurus'],
  ['Righteous', 'Tangerine', 'Unicorn'],
  ['Robotic', 'Teal', 'Velociraptor'],
  ["Rockin'", 'Titanium', 'Walrus'],
  ['Rough', 'Topaz', 'Whale'],
  ['Round', 'Violet', 'Wolf'],
  ['Royal', 'Yellow', 'Zebra'],
  ['Running', 'Amber', 'Beaver'],
  ['Scaly', 'Amethyst', 'Bee'],
  ['Scary', 'Apricot', 'Canary'],
  ['Shadowy', 'Arboreal', 'Cat'],
  ['Shiny', 'Arctic', 'Catfish'],
  ['Shy', 'Banana', 'Centaur'],
  ['Singing', 'Blue', 'Chicken'],
  ['Skating', 'Brass', 'Coyote'],
  ['Skeptical', 'Cave', 'Cricket'],
  ['Skipping', 'Celestial', 'Dinosaur'],
  ['Sleepy', 'Citrine', 'Dog'],
  ['Slippery', 'Cloud', 'Dolphin'],
  ['Slow', 'Cobalt', 'Dragon'],
  ['Small', 'Copper', 'Dragonfly'],
  ['Smiling', 'Crystal', 'Eagle'],
  ['Sneezy', 'Desert', 'Elephant'],
  ['Soaring', 'Diamond', 'Falcon'],
  ['Soft', 'Emerald', 'Flamingo'],
  ['Sparkly', 'Fire', 'Fox'],
  ['Speckled', 'Forest', 'Giraffe'],
  ['Spikey', 'Fuchsia', 'Grasshopper'],
  ['Spirited', 'Gold', 'Griffin'],
  ['Splendid', 'Gray', 'Hamster'],
  ['Spooky', 'Green', 'Hawk'],
  ['Spotted', 'Indigo', 'Hippogriff'],
  ['Spunky', 'Jade', 'Hippopotamus'],
  ['Squeaky', 'Jungle', 'Horse'],
  ['Squishy', 'Lava', 'Inchworm'],
  ['Starry', 'Lavender', 'Kitten'],
  ['Stealthy', 'Lightning', 'Kraken'],
  ['Stellar', 'Lime', 'Lemur'],
  ['Stretchy', 'Magenta', 'Leopard'],
  ['Striped', 'Maroon', 'Lion'],
  ['Strong', 'Moonstone', 'Lizard'],
  ['Super', 'Mountain', 'Manatee'],
  ['Surprised', 'Navy', 'Monkey'],
  ['Swimming', 'Ocean', 'Narwhal'],
  ['Tall', 'Olive', 'Octopus'],
  ['Tame', 'Onyx', 'Parrot'],
  ['Terrific', 'Opal', 'Phoenix'],
  ['Thorny', 'Orange', 'Platypus'],
  ['Thundering', 'Pearl', 'Pony'],
  ['Ticklish', 'Pink', 'Porcupine'],
  ['Tiny', 'Platinum', 'Puppy'],
  ['Traveling', 'Plum', 'Raccoon'],
  ['Tremendous', 'Purple', 'Rooster'],
  ['Triumphant', 'Quartz', 'Seahorse'],
  ['Truthful', 'Rainforest', 'Sloth'],
  ['Twirling', 'Red', 'Slug'],
  ['Ultra', 'River', 'Snail'],
  ['Unbelievable', 'Ruby', 'Sphinx'],
  ['Velvety', 'Sand', 'Squid'],
  ['Visionary', 'Sapphire', 'Squirrel'],
  ['Vivacious', 'Scarlet', 'Stegosaurus'],
  ['Vivid', 'Silver', 'Tiger'],
  ['Vocal', 'Sky', 'Timberwolf'],
  ['Warm', 'Snow', 'Tuna'],
  ['Wild', 'Space', 'Tyrannosaurus'],
  ['Winged', 'Tangerine', 'Unicorn'],
  ['Wise', 'Teal', 'Velociraptor'],
  ['Witty', 'Titanium', 'Walrus'],
  ['Wonderful', 'Topaz', 'Whale'],
  ['Young', 'Violet', 'Wolf'],
  ['Zealous', 'Yellow', 'Zebra'],
  ['Adorable', 'Amber', 'Beaver'],
  ['Adventurous', 'Amethyst', 'Bee'],
  ['Agile', 'Apricot', 'Canary'],
  ['Amazing', 'Arboreal', 'Cat'],
  ['Ancient', 'Arctic', 'Catfish'],
  ['Artistic', 'Banana', 'Centaur'],
  ['Astounding', 'Blue', 'Chicken'],
  ['Athletic', 'Brass', 'Coyote'],
  ['Awesome', 'Cave', 'Cricket'],
  ['Beautiful', 'Celestial', 'Dinosaur'],
  ['Benevolent', 'Citrine', 'Dog'],
  ['Big', 'Cloud', 'Dolphin'],
  ['Blazing', 'Cobalt', 'Dragon'],
  ['Blissful', 'Copper', 'Dragonfly'],
  ['Blushing', 'Crystal', 'Eagle'],
  ['Bold', 'Desert', 'Elephant'],
  ['Bouncy', 'Diamond', 'Falcon'],
  ['Breezy', 'Emerald', 'Flamingo'],
  ['Bright', 'Fire', 'Fox'],
  ['Brilliant', 'Forest', 'Giraffe'],
  ['Bubbly', 'Fuchsia', 'Grasshopper'],
  ['Bumpy', 'Gold', 'Griffin'],
  ['Busy', 'Gray', 'Hamster'],
  ['Calm', 'Green', 'Hawk'],
  ['Camouflaged', 'Indigo', 'Hippogriff'],
  ['Carefree', 'Jade', 'Hippopotamus'],
  ['Caring', 'Jungle', 'Horse'],
  ['Carnivorous', 'Lava', 'Inchworm'],
  ['Charming', 'Lavender', 'Kitten'],
  ['Cheerful', 'Lightning', 'Kraken'],
  ['Cheesy', 'Lime', 'Lemur'],
  ['Classy', 'Magenta', 'Leopard'],
  ['Colossal', 'Maroon', 'Lion'],
  ['Comfortable', 'Moonstone', 'Lizard'],
  ['Cool', 'Mountain', 'Manatee'],
  ['Corny', 'Navy', 'Monkey'],
  ['Courageous', 'Ocean', 'Narwhal'],
  ['Cozy', 'Olive', 'Octopus'],
  ['Crawling', 'Onyx', 'Parrot'],
  ['Crazy', 'Opal', 'Phoenix'],
  ['Creative', 'Orange', 'Platypus'],
  ['Cuddly', 'Pearl', 'Pony'],
  ['Cunning', 'Pink', 'Porcupine'],
  ['Dainty', 'Platinum', 'Puppy'],
  ['Dancing', 'Plum', 'Raccoon'],
  ['Dapper', 'Purple', 'Rooster'],
  ['Daring', 'Quartz', 'Seahorse'],
  ['Dark', 'Rainforest', 'Sloth'],
  ['Dashing', 'Red', 'Slug'],
  ['Delightful', 'River', 'Snail'],
  ['Deluxe', 'Ruby', 'Sphinx'],
  ['Determined', 'Sand', 'Squid'],
  ['Doubtful', 'Sapphire', 'Squirrel'],
  ['Dreaming', 'Scarlet', 'Stegosaurus'],
  ['Dry', 'Silver', 'Tiger'],
  ['Educated', 'Sky', 'Timberwolf'],
  ['Elder', 'Snow', 'Tuna'],
  ['Endearing', 'Space', 'Tyrannosaurus'],
  ['Energetic', 'Tangerine', 'Unicorn'],
  ['Engaging', 'Teal', 'Velociraptor'],
  ['Enormous', 'Titanium', 'Walrus'],
  ['Entertaining', 'Topaz', 'Whale'],
  ['Exciting', 'Violet', 'Wolf'],
  ['Extraordinary', 'Yellow', 'Zebra'],
  ['Fanciful', 'Amber', 'Beaver'],
  ['Fantastic', 'Amethyst', 'Bee'],
  ['Fast', 'Apricot', 'Canary'],
  ['Fearless', 'Arboreal', 'Cat'],
  ['Feathered', 'Arctic', 'Catfish'],
  ['Feisty', 'Banana', 'Centaur'],
  ['Feral', 'Blue', 'Chicken'],
  ['Fierce', 'Brass', 'Coyote'],
  ['Floppy', 'Cave', 'Cricket'],
  ['Fluffy', 'Celestial', 'Dinosaur'],
  ['Flying', 'Citrine', 'Dog'],
  ['Friendly', 'Cloud', 'Dolphin'],
  ['Frosty', 'Cobalt', 'Dragon'],
  ['Funny', 'Copper', 'Dragonfly'],
  ['Furry', 'Crystal', 'Eagle'],
  ['Fuzzy', 'Desert', 'Elephant'],
  ['Galactic', 'Diamond', 'Falcon'],
  ['Gargantuan', 'Emerald', 'Flamingo'],
  ['Generous', 'Fire', 'Fox'],
  ['Gentle', 'Forest', 'Giraffe'],
  ['Genuine', 'Fuchsia', 'Grasshopper'],
  ['Giant', 'Gold', 'Griffin'],
  ['Giggly', 'Gray', 'Hamster'],
  ['Ginormous', 'Green', 'Hawk'],
  ['Glacial', 'Indigo', 'Hippogriff'],
  ['Glamorous', 'Jade', 'Hippopotamus'],
  ['Gleeful', 'Jungle', 'Horse'],
  ['Glistening', 'Lava', 'Inchworm'],
  ['Glittery', 'Lavender', 'Kitten'],
  ['Glossy', 'Lightning', 'Kraken'],
  ['Glowing', 'Lime', 'Lemur'],
  ['Good', 'Magenta', 'Leopard'],
  ['Goofy', 'Maroon', 'Lion'],
  ['Gorgeous', 'Moonstone', 'Lizard'],
  ['Graceful', 'Mountain', 'Manatee'],
  ['Great', 'Navy', 'Monkey'],
  ['Groovy', 'Ocean', 'Narwhal'],
  ['Grumpy', 'Olive', 'Octopus'],
  ['Gutsy', 'Onyx', 'Parrot'],
  ['Hairy', 'Opal', 'Phoenix'],
  ['Happy', 'Orange', 'Platypus'],
  ['Heavy', 'Pearl', 'Pony'],
  ['Helpful', 'Pink', 'Porcupine'],
  ['Heroic', 'Platinum', 'Puppy'],
  ['Hidden', 'Plum', 'Raccoon'],
  ['Hopeful', 'Purple', 'Rooster'],
  ['Hopping', 'Quartz', 'Seahorse'],
  ['Huge', 'Rainforest', 'Sloth'],
  ['Humongous', 'Red', 'Slug'],
  ['Humorous', 'River', 'Snail'],
  ['Hungry', 'Ruby', 'Sphinx'],
  ['Hyper', 'Sand', 'Squid'],
  ['Icy', 'Sapphire', 'Squirrel'],
  ['Idealistic', 'Scarlet', 'Stegosaurus'],
  ['Imaginative', 'Silver', 'Tiger'],
  ['Impressive', 'Sky', 'Timberwolf'],
  ['Incredible', 'Snow', 'Tuna'],
  ['Ingenious', 'Space', 'Tyrannosaurus'],
  ['Inky', 'Tangerine', 'Unicorn'],
  ['Innovative', 'Teal', 'Velociraptor'],
  ['Inspiring', 'Titanium', 'Walrus'],
  ['Intellectual', 'Topaz', 'Whale'],
  ['Interesting', 'Violet', 'Wolf'],
  ['Interstellar', 'Yellow', 'Zebra'],
  ['Intrepid', 'Amber', 'Beaver'],
  ['Itty-Bitty', 'Amethyst', 'Bee'],
  ['Jazzy', 'Apricot', 'Canary'],
  ['Jiggly', 'Arboreal', 'Cat'],
  ['Joking', 'Arctic', 'Catfish'],
  ['Jovial', 'Banana', 'Centaur'],
  ['Joyful', 'Blue', 'Chicken'],
  ['Jumpy', 'Brass', 'Coyote'],
  ['Lacy', 'Cave', 'Cricket'],
  ['Large', 'Celestial', 'Dinosaur'],
  ['Laughing', 'Citrine', 'Dog'],
  ['Lazy', 'Cloud', 'Dolphin'],
  ['Leafy', 'Cobalt', 'Dragon'],
  ['Light', 'Copper', 'Dragonfly'],
  ['Lively', 'Crystal', 'Eagle'],
  ['Long', 'Desert', 'Elephant'],
  ['Loony', 'Diamond', 'Falcon'],
  ['Loud', 'Emerald', 'Flamingo'],
  ['Lovely', 'Fire', 'Fox'],
  ['Loyal', 'Forest', 'Giraffe'],
  ['Lucky', 'Fuchsia', 'Grasshopper'],
  ['Lyrical', 'Gold', 'Griffin'],
  ['Magical', 'Gray', 'Hamster'],
  ['Magnetic', 'Green', 'Hawk'],
  ['Majestic', 'Indigo', 'Hippogriff'],
  ['Marvelous', 'Jade', 'Hippopotamus'],
  ['Masterful', 'Jungle', 'Horse'],
  ['Mega', 'Lava', 'Inchworm'],
  ['Merry', 'Lavender', 'Kitten'],
  ['Metallic', 'Lightning', 'Kraken'],
  ['Micro', 'Lime', 'Lemur'],
  ['Mighty', 'Magenta', 'Leopard'],
  ['Mini', 'Maroon', 'Lion'],
  ['Mischievous', 'Moonstone', 'Lizard'],
  ['Muscular', 'Mountain', 'Manatee'],
  ['Musical', 'Navy', 'Monkey'],
  ['Mutant', 'Ocean', 'Narwhal'],
  ['Mysterious', 'Olive', 'Octopus'],
  ['Mythical', 'Onyx', 'Parrot'],
  ['Nice', 'Opal', 'Phoenix'],
  ['Nocturnal', 'Orange', 'Platypus'],
  ['Noticeable', 'Pearl', 'Pony'],
  ['Optimistic', 'Pink', 'Porcupine'],
  ['Outdoorsy', 'Platinum', 'Puppy'],
  ['Painted', 'Plum', 'Raccoon'],
  ['Patient', 'Purple', 'Rooster'],
  ['Peaceful', 'Quartz', 'Seahorse'],
  ['Perfect', 'Rainforest', 'Sloth'],
  ['Persistent', 'Red', 'Slug'],
  ['Pigmy', 'River', 'Snail'],
  ['Playful', 'Ruby', 'Sphinx'],
  ['Polite', 'Sand', 'Squid'],
  ['Powerful', 'Sapphire', 'Squirrel'],
  ['Quick', 'Scarlet', 'Stegosaurus'],
  ['Quiet', 'Silver', 'Tiger'],
  ['Quirky', 'Sky', 'Timberwolf'],
  ['Random', 'Snow', 'Tuna'],
  ['Remarkable', 'Space', 'Tyrannosaurus'],
  ['Righteous', 'Tangerine', 'Unicorn'],
  ['Robotic', 'Teal', 'Velociraptor'],
  ["Rockin'", 'Titanium', 'Walrus'],
  ['Rough', 'Topaz', 'Whale'],
  ['Round', 'Violet', 'Wolf'],
  ['Royal', 'Yellow', 'Zebra'],
  ['Running', 'Amber', 'Beaver'],
  ['Scaly', 'Amethyst', 'Bee'],
  ['Scary', 'Apricot', 'Canary'],
  ['Shadowy', 'Arboreal', 'Cat'],
  ['Shiny', 'Arctic', 'Catfish'],
  ['Shy', 'Banana', 'Centaur'],
  ['Singing', 'Blue', 'Chicken'],
  ['Skating', 'Brass', 'Coyote'],
  ['Skeptical', 'Cave', 'Cricket'],
  ['Skipping', 'Celestial', 'Dinosaur'],
  ['Sleepy', 'Citrine', 'Dog'],
  ['Slippery', 'Cloud', 'Dolphin'],
  ['Slow', 'Cobalt', 'Dragon'],
  ['Small', 'Copper', 'Dragonfly'],
  ['Smiling', 'Crystal', 'Eagle'],
  ['Sneezy', 'Desert', 'Elephant'],
  ['Soaring', 'Diamond', 'Falcon'],
  ['Soft', 'Emerald', 'Flamingo'],
  ['Sparkly', 'Fire', 'Fox'],
  ['Speckled', 'Forest', 'Giraffe'],
  ['Spikey', 'Fuchsia', 'Grasshopper'],
  ['Spirited', 'Gold', 'Griffin'],
  ['Splendid', 'Gray', 'Hamster'],
  ['Spooky', 'Green', 'Hawk'],
  ['Spotted', 'Indigo', 'Hippogriff'],
  ['Spunky', 'Jade', 'Hippopotamus'],
  ['Squeaky', 'Jungle', 'Horse'],
  ['Squishy', 'Lava', 'Inchworm'],
  ['Starry', 'Lavender', 'Kitten'],
  ['Stealthy', 'Lightning', 'Kraken'],
  ['Stellar', 'Lime', 'Lemur'],
  ['Stretchy', 'Magenta', 'Leopard'],
  ['Striped', 'Maroon', 'Lion'],
  ['Strong', 'Moonstone', 'Lizard'],
  ['Super', 'Mountain', 'Manatee'],
  ['Surprised', 'Navy', 'Monkey'],
  ['Swimming', 'Ocean', 'Narwhal'],
  ['Tall', 'Olive', 'Octopus'],
  ['Tame', 'Onyx', 'Parrot'],
  ['Terrific', 'Opal', 'Phoenix'],
  ['Thorny', 'Orange', 'Platypus'],
  ['Thundering', 'Pearl', 'Pony'],
  ['Ticklish', 'Pink', 'Porcupine'],
  ['Tiny', 'Platinum', 'Puppy'],
  ['Traveling', 'Plum', 'Raccoon'],
  ['Tremendous', 'Purple', 'Rooster'],
  ['Triumphant', 'Quartz', 'Seahorse'],
  ['Truthful', 'Rainforest', 'Sloth'],
  ['Twirling', 'Red', 'Slug'],
  ['Ultra', 'River', 'Snail'],
  ['Unbelievable', 'Ruby', 'Sphinx'],
  ['Velvety', 'Sand', 'Squid'],
  ['Visionary', 'Sapphire', 'Squirrel'],
  ['Vivacious', 'Scarlet', 'Stegosaurus'],
  ['Vivid', 'Silver', 'Tiger'],
  ['Vocal', 'Sky', 'Timberwolf'],
  ['Warm', 'Snow', 'Tuna'],
  ['Wild', 'Space', 'Tyrannosaurus'],
  ['Winged', 'Tangerine', 'Unicorn'],
  ['Wise', 'Teal', 'Velociraptor'],
  ['Witty', 'Titanium', 'Walrus'],
  ['Wonderful', 'Topaz', 'Whale'],
  ['Young', 'Violet', 'Wolf'],
  ['Zealous', 'Yellow', 'Zebra']
];

const blacklistArray = ['ANL',
  'ANS',
  'ASS',
  'AZN',
  'BCH',
  'CAC',
  'CAK',
  'CAQ',
  'CLT',
  'CNT',
  'COC',
  'COK',
  'COQ',
  'CUM',
  'DCK',
  'DIC',
  'DIK',
  'DIQ',
  'DIX',
  'DMN',
  'DSH',
  'DYC',
  'DYK',
  'DYQ',
  'FAG',
  'FAP',
  'FCK',
  'FCU',
  'FGT',
  'FKU',
  'FOB',
  'FQU',
  'FTP',
  'FUC',
  'FUK',
  'FUQ',
  'FUX',
  'GAI',
  'GAY',
  'GEI',
  'GEY',
  'GIZ',
  'GUC',
  'GUK',
  'GUQ',
  'GVR',
  'GZZ',
  'HOR',
  'JAP',
  'JEW',
  'JIZ',
  'JOO',
  'JYZ',
  'JZZ',
  'KAC',
  'KAK',
  'KAQ',
  'KIK',
  'KKK',
  'KLT',
  'KNT',
  'KOC',
  'KOK',
  'KOQ',
  'KOX',
  'KUM',
  'KYC',
  'KYK',
  'KYQ',
  'LCK',
  'LIC',
  'LIK',
  'LIQ',
  'LOL',
  'LSD',
  'MFF',
  'MIC',
  'MIK',
  'MIQ',
  'MLF',
  'MUF',
  'MYC',
  'MYK',
  'MYQ',
  'NAD',
  'NDS',
  'NDZ',
  'NGR',
  'NIG',
  'NUT',
  'NWA',
  'ORL',
  'OPP',
  'PCP',
  'PHC',
  'PHK',
  'PHQ',
  'PIS',
  'PMS',
  'PNS',
  'POO',
  'POT',
  'PRC',
  'PRK',
  'PRN',
  'PRQ',
  'PSS',
  'PSY',
  'PUS',
  'RAC',
  'RAK',
  'RAQ',
  'RCK',
  'SAC',
  'SAK',
  'SAQ',
  'SCK',
  'SEX',
  'SFU',
  'SHT',
  'SJV',
  'SLT',
  'SNM',
  'SOB',
  'SOL',
  'STD',
  'SUC',
  'SUK',
  'SUQ',
  'SXE',
  'SXI',
  'SXX',
  'SXY',
  'THC',
  'TIT',
  'TOC',
  'TOK',
  'TOQ',
  'TWT',
  'VAG',
  'VAJ',
  'VGN',
  'VJN',
  'WAC',
  'WAK',
  'WAQ',
  'WCK',
  'WOP',
  'WTF',
  'XTC',
  'XXX',
  'AZS',
  'AZZ'
];

const fullTranslationTable = {
  en: {
    say_this: 'Say This',
    find_robots: 'Find Robots',
    finding_robots: 'Finding Robots',
    connected: 'Connected',
    start_programming: 'Start Programming',
    device_disconnected: 'Device (A or B) Disconnected',
    reconnecting: 'Reconnecting',
    connect_dongle: 'Connect Bluetooth Dongle',
    CompassCalibrate: 'Calibrate Compass',
    Update_firmware: 'Update Firmware',
    Connection_Failure: 'Connection Failure'
  },
  ko: {
    say_this: '(Slot 1 = 안녕!) 말하기',
    find_robots: '로봇 찾기',
    finding_robots: '로봇 찾는 중',
    connected: '연결 완료',
    start_programming: '프로그래밍 시작하기',
    device_disconnected: '기기 (A 또는 B) 연결 끊김',
    reconnecting: '다시 연결 중',
    connect_dongle: '블루투스 동글 연결하기',
    CompassCalibrate: '나침반 센서 보정',
    Update_firmware: '펌웨어 업데이트',
    Connection_Failure: '연결 실패'
  },
  de: {
    say_this: 'Sage',
    find_robots: 'Suche Roboter',
    finding_robots: 'Suche Roboter',
    connected: 'Verbunden',
    start_programming: 'Beginne Programmierung',
    device_disconnected: 'Gerät (A oder B) getrennt',
    reconnecting: 'Wiederverbinden',
    connect_dongle: 'Verbinde Bluetooth Dongle',
    CompassCalibrate: 'Kompass kalibrieren',
    Update_firmware: 'Firmware Updaten',
    Connection_Failure: 'Verbindung fehlgeschlagen'
  },
  pt: {
    say_this: 'Diga Isso',
    find_robots: 'Encontre Robôs',
    finding_robots: 'Encontrando Robôs',
    connected: 'Conectado',
    start_programming: 'Iniciar a programação',
    device_disconnected: 'Dispositivo (A ou B) Desconectado',
    reconnecting: 'Reconectando',
    connect_dongle: 'Conecte o Dongle Bluetooth',
    CompassCalibrate: 'Calibrar Bússola',
    Update_firmware: 'Atualizar Firmware',
    Connection_Failure: 'Falha na Conexão'
  },
  fr: {
    say_this: 'Dites ceci',
    find_robots: 'Trouvez des robots',
    finding_robots: 'Trouver des robots',
    connected: 'Connecté',
    start_programming: 'Lancez la programmation',
    device_disconnected: 'Le Périphérique (A ou B) déconnecté',
    reconnecting: 'Reconnecter',
    connect_dongle: 'Connectez le bluetooth dongle',
    CompassCalibrate: 'Calibrer le compas',
    Update_firmware: 'Mettez à Jour le Firmware',
    Connection_Failure: 'Échec de connexion'
  },
  nl: {
    say_this: 'Zeg Dit',
    find_robots: 'Zoek Naar Robots',
    finding_robots: 'Zoeken Naar Robots',
    connected: 'Verbonden',
    start_programming: 'Begin met Programmeren',
    device_disconnected: 'Apparaat (A of B) Losgekoppeld',
    reconnecting: 'Verbinding Opniew Maken',
    connect_dongle: 'Sluit Bluetooth-dongle aan',
    CompassCalibrate: 'Kompas Kalibreren',
    Update_firmware: 'Update Firmware',
    Connection_Failure: 'Verbindingsfout'
  },
  zh_Hans: {
    say_this: '说',
    find_robots: '寻找机器人',
    finding_robots: '寻找机器人中',
    connected: '已连接',
    start_programming: '开始编程',
    device_disconnected: '设备（A或B）已断开连接',
    reconnecting: '重新连接',
    connect_dongle: '连接蓝牙',
    CompassCalibrate: '校准指南针',
    Update_firmware: '更新固件',
    Connection_Failure: '连接失败'
  },
  zh_Hant: {
    say_this: '說',
    find_robots: '尋找機器人',
    finding_robots: '尋找機器人中',
    connected: '已連接',
    start_programming: '開始編程',
    device_disconnected: '設備（A或B）已斷開連接',
    reconnecting: '重新連接',
    connect_dongle: '連接藍牙',
    CompassCalibrate: '校準指南針',
    Update_firmware: '更新固件',
    Connection_Failure: '連接失敗'
  },
  ar: {
    say_this: 'قل هذا',
    find_robots: 'ابحث عن روبوت',
    finding_robots: 'إيجاد روبوت',
    connected: 'متصل',
    start_programming: 'ابدأ البرمجة',
    device_disconnected: 'الجهاز أ أو ب غير متصل',
    reconnecting: 'إعادة الاتصال',
    connect_dongle: 'اتصال عن طريق البلوتوث',
    CompassCalibrate: 'معايرة البوصلة',
    Update_firmware: 'تحديث البرامج الثابتة',
    Connection_Failure: 'فشل الاتصال'
  },
  da: {
    say_this: 'Sig dette',
    find_robots: 'Find robotter',
    finding_robots: 'Finder robotter',
    connected: 'Forbundet',
    start_programming: 'Start programmering',
    device_disconnected: 'Forbindelse til enhed (A eller B) er afbrudt',
    reconnecting: 'Opretter forbindelse igen',
    connect_dongle: 'Forbind bluetooth dongle',
    CompassCalibrate: 'Kalibrér kompas',
    Update_firmware: 'Opdatér Firmware',
    Connection_Failure: 'Forbindelse mislykket'
  },
  he: {
    say_this: 'להגיד',
    find_robots: 'למצוא רובוטים',
    finding_robots: 'מחפשים רובוטים',
    connected: 'מחובר',
    start_programming: 'התחל תכנות',
    device_disconnected: 'עתקן ( א או ב) מנותק',
    reconnecting: 'מחברים מחדש',
    connect_dongle: 'מחברים הדונגל לבלוטוס',
    CompassCalibrate: 'כיול מצפן',
    Update_firmware: 'עדכון קשוחה',
    Connection_Failure: 'חיבור נכשל'
  },
  es: {
    say_this: 'Decir esto',
    find_robots: 'Encontrar robots',
    finding_robots: 'Encontrando robots',
    connected: 'Conectado',
    start_programming: 'Iniciar programacion',
    device_disconnected: 'Dispositivo (A o B) Desconectado',
    reconnecting: 'Reconectando',
    connect_dongle: 'Conectar el dongle del bluethoot',
    CompassCalibrate: 'Calibrar la brujula',
    Update_firmware: 'Actualizar Firmware',
    Connection_Failure: 'Coneccion fallada'
  },
  ca: {
    say_this: 'Digues això',
    find_robots: 'Cerca robots',
    finding_robots: 'Cercant robots',
    connected: 'Connectat',
    start_programming: 'Comença a programar',
    device_disconnected: 'Dispositiu (A o B) desconnectat',
    reconnecting: 'Reconnectant',
    connect_dongle: 'Connecta llapis Bluetooth',
    CompassCalibrate: 'Calibratge de la brúixola',
    Update_firmware: 'Actualitza el Firmware',
    Connection_Failure: 'Error de connexió'
  },
  fi: {
    say_this: 'Sano tämä',
    find_robots: 'Etsi robotteja',
    finding_robots: 'Etsii robotteja',
    connected: 'Yhdistetty',
    start_programming: 'Aloita ohjelmointi',
    device_disconnected: 'Yhteys katkennut laitteeseen (A tai B)',
    reconnecting: 'Yhdistää uudelleen',
    connect_dongle: 'Yhdistä Bluetooth-palikka',
    CompassCalibrate: 'Kalibroi kompassi',
    Update_firmware: 'Päivitä laiteohjelma',
    Connection_Failure: 'Virhe yhdistettäessä'
  },
  sv: {
    say_this: 'Säg detta',
    find_robots: 'Hitta robotar',
    finding_robots: 'Hittar robotar',
    connected: 'Kopplade',
    start_programming: 'Börja programmera',
    device_disconnected: 'Enhet (A eller B) frånkopplad',
    reconnecting: 'Omkopplar',
    connect_dongle: 'Koppla Bluetooth dosa',
    CompassCalibrate: 'Kalibrera kompass',
    Update_firmware: 'Uppdatera Programvara',
    Connection_Failure: 'Problem med kopplingen'
  }
};

function getDeviceFancyName(devName) {
  if ((devName.startsWith("MB")) || (devName.startsWith("BB")) || (devName.startsWith("FN"))) {
    //console.log("Code: " + devName.substr(devName.length - 5));

    var numberInDec = parseInt(devName.substr(devName.length - 5), 16);
    //console.log("numberInDec " + numberInDec);
    var mod16 = numberInDec % 16;
    //console.log("mod16 " + mod16);
    var top8 = numberInDec % 256;
    //console.log("top8 " + top8);
    var mid6 = (numberInDec / 256) % 64;
    //console.log("mid6 " + mid6);
    var bot6 = (numberInDec / 256) / 64;
    //console.log("bot6 " + bot6);

    var first = Math.floor(top8 + mod16);
    var second = Math.floor(mid6 + mod16);
    var third = Math.floor(bot6 + mod16);

    //console.log("first, second, third: " + first + ", " + second + ", " + third);

    var names = fancyNameArray;
    var fancyName = names[first][0] + " " + names[second][1] + " " + names[third][2];
    var initials = names[first][0].charAt(0) + names[second][1].charAt(0) + names[third][2].charAt(0);

    while (blacklistArray.includes(initials)) {
      console.log("Found bad word: {} in {}" + initials + " " + fancyName);
      // add 1 and mod the result by 512 to the index of the second word:
      second++;
      second %= 512;
      fancyName = names[first][0] + " " + names[second][1] + " " + names[third][2];
      initials = names[first][0].charAt(0) + names[second][1].charAt(0) + names[third][2].charAt(0);
    }

    fancyName += " (" + initials + ")";
    console.log("Fancy Name assigned to device: " + fancyName);
    return fancyName;
  }
}

function translateStrings(table) {
  var translationTable = table;
  // Set up defaults
  //$('#findBtnText').text(" "+translationTable["finding_robots"]);
  $('#connection-state').html(translationTable["connected"]);
  $('#start_programming').html(translationTable["start_programming"]);
  $('#Connection_Failure').html(" " + translationTable["Connection_Failure"] + " ");
  $('#CompassCalibrate').html(" " + translationTable["CompassCalibrate"]);
  // Multiple update_firmware tags on prototype.html
  $('#Update_firmware').html(translationTable["Update_firmware"]);
  $('#Update_firmware1').html(translationTable["Update_firmware"]);
  $('#Update_firmware2').html(translationTable["Update_firmware"]);
  $('#Update_firmware3').html(translationTable["Update_firmware"]);
}

function setLanguage() {
  var language = window.navigator.language;
  console.log("window.navigator.language = " + language);

  if (language.startsWith("zh")) {
    if (language == "zh-TW") { language = "zh_Hant"; } // Specify trad chinese
    else { language = "zh_Hans"; } // Default to simplified chinese for any other variant
  } else {
    language = language.substring(0, 2); // require the 2 letter code.
  }
  // Convert old code for Hebrew to new
  if (language == "iw") { language = "he"; }

  console.log("Language code used: " + language);

  var thisLocaleTable = fullTranslationTable[language];
  if (thisLocaleTable === null) {
    console.log("Language unsupported. Defaulting to English (en)");
    language = "en";
    thisLocaleTable = fullTranslationTable[language]; // populate the locale phrases
  }

  console.log("thisLocaleTable:");
  console.log(thisLocaleTable);

  translateStrings(thisLocaleTable);
}
